name: waterflyiii
description: WaterFly III, a mobile client for Firefly III
publish_to: 'none'

version: 0.3.0-beta

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: any
  intl: any
  path_provider: ^2.0.13
  collection: ^1.18.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  chopper: ^7.0.9
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  infinite_scroll_pagination: ^4.0.0
  badges: ^3.1.2
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.2
  open_filex: ^4.3.4
  file_picker: ^6.0.0
  animations: ^2.0.10
  flutter_local_notifications: ^16.2.0
  notifications_listener_service:
    git:
      url: https://github.com/dreautall/notification_listener_service.git
      ref: 280a7b869fe57c81dd1842cd08fa16045d828f0a
  device_apps: ^2.2.0
  package_info_plus: ^5.0.1
  logging: ^1.1.1
  flutter_email_sender: ^6.0.2
  local_auth: ^2.1.6
  dynamic_color: ^1.6.8
  material_color_utilities: ^0.5.0
  version: ^3.0.2
  quick_actions: ^1.0.6
  stock: ^1.1.0
  syncfusion_flutter_charts: ^23.2.7
  image_picker: ^1.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  # needed for swagger_dart_code_generator
  build_runner: ^2.4.7
  chopper_generator: ^7.0.6
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.13.5
  flutter_native_splash: ^2.3.8
  translations_cleaner: ^0.0.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg

flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#fdfcfe"
  color_dark: "#1a1c1e"