name: waterflyiii
description: WaterFly III, a mobile client for Firefly III
publish_to: 'none'

version: 0.1.5-beta

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.0.13
  collection: ^1.17.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  chopper: ^6.0.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.8
  infinite_scroll_pagination: ^3.2.0
  badges: ^3.1.1
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.1
  open_filex: ^4.3.2
  file_picker: ^5.2.9
  animations: ^2.0.7
  flutter_local_notifications: ^14.0.0+1
  notifications_listener_service:
    git:
      url: https://github.com/dreautall/notification_listener_service.git
      ref: 280a7b869fe57c81dd1842cd08fa16045d828f0a
  device_apps: ^2.2.0
  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  # needed for swagger_dart_code_generator
  build_runner: ^2.1.7
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.0
  swagger_dart_code_generator: ^2.10.4
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg

flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#fdfcfe"
  color_dark: "#1a1c1e"