name: waterflyiii
description: WaterFly III, a mobile client for Firefly III
publish_to: 'none'

version: 1.0.9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: any
  intl: any
  path_provider: ^2.1.4
  collection: ^1.18.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  chopper: ^8.0.2
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.4
  infinite_scroll_pagination: ^4.0.0
  badges: ^3.1.2
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.2
  file_picker: ^8.1.2
  animations: ^2.0.11
  flutter_local_notifications: ^18.0.1
  notifications_listener_service:
    git:
      url: https://github.com/dreautall/notification_listener_service.git
      ref: 5f0d49d1b133943a6e6449059712514bf6506fd1
  appcheck:
    git:
      url: https://github.com/bugrevealingbme/AppCheck.git
      ref: ce371398f86412a8d9a2e0b75a9b51597ea1d79f
  package_info_plus: ^8.0.2
  logging: ^1.1.1
  flutter_email_sender: ^6.0.2
  local_auth: ^2.1.8
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  version: ^3.0.2
  quick_actions: ^1.0.7
  stock: ^1.1.0
  syncfusion_flutter_charts: ^27.1.48
  image_picker: ^1.0.7
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  flutter_sharing_intent: ^1.1.1
  http: ^1.2.1
  open_file_plus: ^3.4.1+1
  cronet_http: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  # needed for swagger_dart_code_generator
  build_runner: ^2.4.7
  chopper_generator: ^8.0.2
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^3.0.0
  flutter_native_splash: ^2.3.10
  translations_cleaner: ^0.0.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg

flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#fdfcfe"
  color_dark: "#1a1c1e"