name: waterflyiii
description: Waterfly III, a mobile client for Firefly III
publish_to: 'none'

version: 1.1.1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: any
  intl: any
  path_provider: ^2.1.4
  collection: ^1.19.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  chopper: ^8.0.2
  json_annotation: ^4.8.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.4
  infinite_scroll_pagination: ^5.0.0
  badges: ^3.1.2
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.2
  file_picker: ^10.1.8
  animations: ^2.0.11
  flutter_local_notifications: ^19.0.0
  notifications_listener_service:
    git:
      url: https://github.com/dreautall/notification_listener_service.git
      ref: main
  appcheck:
    git:
      url: https://github.com/bugrevealingbme/AppCheck.git
      ref: ce371398f86412a8d9a2e0b75a9b51597ea1d79f
  package_info_plus: ^8.2.0
  logging: ^1.1.1
  flutter_email_sender: ^7.0.0
  local_auth: ^2.1.8
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  version: ^3.0.2
  quick_actions: ^1.0.7
  stock: ^1.1.0
  syncfusion_flutter_charts: ^29.1.33
  image_picker: ^1.0.7
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0
  flutter_sharing_intent: ^1.1.1
  http: ^1.2.1
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
      ref: main
  cronet_http: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  # needed for swagger_dart_code_generator
  build_runner: ^2.4.13
  chopper_generator: ^8.0.3
  json_serializable: ^6.9.0
  swagger_dart_code_generator: ^3.0.1
  flutter_native_splash: ^2.4.6
  translations_cleaner: ^0.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#fdfcfe"
  color_dark: "#1a1c1e"