name: waterflyiii
description: WaterFly III, a mobile client for Firefly III
publish_to: 'none'

version: 0.1.8-beta

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.0.13
  collection: ^1.17.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  chopper: ^6.1.2
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.8
  infinite_scroll_pagination: ^3.2.0
  badges: ^3.1.1
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.1
  open_filex: ^4.3.2
  file_picker: ^5.3.0
  animations: ^2.0.7
  flutter_local_notifications: ^15.0.0
  notifications_listener_service:
    git:
      url: https://github.com/dreautall/notification_listener_service.git
      ref: 280a7b869fe57c81dd1842cd08fa16045d828f0a
  device_apps: ^2.2.0
  package_info_plus: ^4.0.0
  logging: ^1.1.1
  flutter_email_sender: ^6.0.1
  local_auth: ^2.1.6
  dynamic_color: ^1.6.5
  material_color_utilities: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.2
  # needed for swagger_dart_code_generator
  build_runner: ^2.4.6
  chopper_generator: ^6.0.2
  json_serializable: ^6.6.0
  swagger_dart_code_generator: ^2.11.5
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg

flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#fdfcfe"
  color_dark: "#1a1c1e"