name: waterflyiii
description: WaterFly III, a mobile client for Firefly III
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.11-alpha

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.0.13
  collection: ^1.17.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  chopper: ^6.0.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.8
  infinite_scroll_pagination: ^3.2.0
  badges: ^3.1.0
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.1
  open_filex: ^4.3.2
  file_picker: ^5.2.7
  animations: ^2.0.7
  flutter_local_notifications: ^13.0.0
  notifications_listener_service:
    git: https://github.com/dreautall/notification_listener_service.git
  device_apps: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # needed for swagger_dart_code_generator
  build_runner: ^2.1.7
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.0
  swagger_dart_code_generator: ^2.10.3
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#ffffff"